Port 2to3 v11
dreambits/Odoo-addons pull request #2
Opened 2018-10-02 15:39 UTC by devang-dreambits

POrting code vai 2to3 and making it compatible for v11.

2018-10-04 02:07 UTC, karan-dreambits requested changes

2018-10-04 02:07 UTC, karan-dreambits commented on dbt_shipment_base/models/Shipment.py
> +    PY3 = True
Do you find any need to maintain py2.7 code for module specific to odoov11 ?

2018-10-04 02:07 UTC, karan-dreambits commented on dbt_shipment_base/views/shipment_transporter_view.xml
>          <record id="action_shipment_transporters" model="ir.actions.act_window">
Why extra space ?

2018-10-04 02:07 UTC, karan-dreambits commented on dbt_shipment_base/views/res_company_view.xml
> +
Why so many extra space ?

2018-10-05 05:59 UTC, karan-dreambits commented on dbt_shipment_base/models/Shipment.py
> +PY3 = False
@devang-dreambits  Is this still needed ?

2018-10-05 09:17 UTC, devang-dreambits commented on dbt_shipment_base/views/res_company_view.xml
> +
spaces are removed.

2018-10-09 08:50 UTC, closed without merging